services:

  db:
    image: postgres
    container_name: postgres_container

    environment:
      POSTGRES_DB: zytho_postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./src/data/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  api:
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: api_container
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=zytho_postgres_db
    depends_on:
      - db

volumes:
  postgres_db: